예외 처리

**try -** try내부에서 예외가 있는지 탐색을 하는 부분
**throw -** try에서 에외를 탐색하면 throw의 인자로 준 변수를 catch로 던진다.
**catch -** throw에서 던진 변수를 인자로 받아서 catch 내부(중괄호 안)에 프로그래머가 정의한 예외처리를 실시



예외가 발생했을때 throw를 통해서 인자로 보내고, catch 부분이 실행이 되고, try내부에서 throw 이후 부분은 skip하게 된다.

기본 문법

```c++
try{
    if(예외 조건)  //조건이 참이면 if문 실행
        throw b;
}

catch(int expn)  // //throw에서 보낸 b 인자를 expn으로 받는다.
{
   // 예외가 나왔을때의 동작
}
```

> `catch (int )`  대신 `catch (...)` 를 사용하면 throw반환 인자가 무엇이든 다 받는다. 